<?php

namespace App\Enums;

enum Career: string
{
    case MECATRONICA_AUTOMATIZACION = 'TÉCNICO SUPERIOR UNIVERSITARIO EN MECATRÓNICA ÁREA AUTOMATIZACIÓN';
    case TI_DESARROLLO_SOFTWARE = 'TÉCNICO SUPERIOR UNIVERSITARIO EN TECNOLOGÍAS DE LA INFORMACIÓN ÁREA DESARROLLO DE SOFTWARE MULTIPLATAFORMA';
    case NEGOCIOS_MERCADOTECNIA = 'TÉCNICO SUPERIOR UNIVERSITARIO EN DESARROLLO DE NEGOCIOS ÁREA MERCADOTECNIA';
    case LIC_INNOVACION_NEGOCIOS_MERCADOTECNIA = 'LICENCIATURA EN INNOVACIÓN DE NEGOCIOS Y MERCADOTECNIA';
    case ING_DESARROLLO_GESTION_SOFTWARE = 'INGENIERÍA EN DESARROLLO Y GESTIÓN DE SOFTWARE';
    case ING_MANTENIMIENTO_INDUSTRIAL = 'INGENIERÍA EN MANTENIMIENTO INDUSTRIAL';
    case ING_MECATRONICA = 'INGENIERÍA EN MECATRÓNICA';
    case ING_MINERIA = 'INGENIERIA EN MINERÍA';
    case ING_PROCESOS_OPERACIONES_INDUSTRIALES = 'INGENIERÍA EN PROCESOS Y OPERACIONES INDUSTRIALES';
    case ING_REDES_INTELIGENTES_CIBERSEGURIDAD = 'INGENIERÍA EN REDES INTELIGENTES Y CIBERSEGURIDAD';
    case LIC_GESTION_CAPITAL_HUMANO = 'LICENCIATURA EN GESTIÓN DEL CAPITAL HUMANO';
    case LIC_TERAPIA_FISICA = 'LICENCIATURA EN TERAPIA FÍSICA';
    case TSU_ADMINISTRACION_CAPITAL_HUMANO = 'TÉCNICO SUPERIOR UNIVERSITARIO EN ADMINISTRACIÓN ÁREA CAPITAL HUMANO';
    case TSU_AGRICULTURA_SUSTENTABLE_PROTEGIDA = 'TÉCNICO SUPERIOR UNIVERSITARIO EN AGRICULTURA SUSTENTABLE Y PROTEGIDA';
    case TSU_ENERGIAS_RENOVABLES_CALIDAD_AHORRO_ENERGIA = 'TECNICO SUPERIOR UNIVERSITARIO ENERGÍAS RENOVABLES ÁREA CALIDAD Y AHORRO DE ENERGÍA';
    case TSU_MANTENIMIENTO_INDUSTRIAL = 'TÉCNICO SUPERIOR UNIVERSITARIO EN MANTENIMIENTO ÁREA INDUSTRIAL';
    case TSU_MANTENIMIENTO_MAQUINARIA_PESADA = 'TÉCNICO SUPERIOR UNIVERSITARIO EN MANTENIMIENTO ÁREA MAQUINARIA PESADA';
    case TSU_MECATRONICA_SISTEMAS_MANUFACTURA_FLEXIBLE = 'TÉCNICO SUPERIOR UNIVERSITARIO EN MECATRÓNICA ÁREA SISTEMAS DE MANUFACTURA FLEXIBLE';
    case TSU_MINERIA_BENEFICIO_MINERO = 'TÉCNICO SUPERIOR UNIVERSITARIO EN MINERÍA ÁREA BENEFICIO MINERO';
    case TSU_PROCESOS_INDUSTRIALES_AUTOMOTRIZ = 'TÉCNICO SUPERIOR UNIVERSITARIO EN PROCESOS INDUSTRIALES ÁREA AUTOMOTRIZ';
    case TSU_PROCESOS_INDUSTRIALES_MANUFACTURA = 'TÉCNICO SUPERIOR UNIVERSITARIO EN PROCESOS INDUSTRIALES ÁREA MANUFACTURA';
    case TSU_TI_ENTORNOS_VIRTUALES_NEGOCIOS_DIGITALES = 'TÉCNICO SUPERIOR UNIVERSITARIO EN TECNOLOGÍAS DE LA INFORMACIÓN ÁREA ENTORNOS VIRTUALES Y NEGOCIOS DIGITALES';
    case TSU_TERAPIA_FISICA_REHABILITACION = 'TÉCNICO SUPERIOR UNIVERSITARIO EN TERAPIA FÍSICA ÁREA REHABILITACIÓN';
    case ING_ENERGIAS_RENOVABLES = 'INGENIERÍA EN ENERGÍAS RENOVABLES';
}
